FROM node:20-slim

WORKDIR /app/frontend

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Открываем порт
EXPOSE 3000

# Команда для запуска
CMD ["npm", "start"] 