version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - backend_static:/app/backend/staticfiles
      - backend_media:/app/backend/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=myhoneydb
      - MYSQL_USER=honeyuser
      - MYSQL_PASSWORD=securepass123
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  backend_static:
  backend_media: 