# Generated by Django 5.1.4 on 2025-06-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт производителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='manuals/', verbose_name='Инструкция (PDF)'),
        ),
    ]
