# Generated by Django 5.1.4 on 2025-06-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_manufacturer_website_product_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manual',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
