# Generated by Django 5.1.4 on 2025-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_allow_null_price_at_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, help_text='Официальный сайт производителя', null=True, verbose_name='Сайт производителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual',
            field=models.FileField(blank=True, help_text='Инструкция по использованию продукта', null=True, upload_to='manuals/', verbose_name='Инструкция (PDF)'),
        ),
    ]
