# Generated by Django 5.1.4 on 2025-06-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_filefield_urlfield_demo'),
    ]

    operations = [
        # Удаляем таблицы asexam - они были только для тестов
        migrations.RunSQL(
            "DROP TABLE IF EXISTS shop_asexam_users;",
            reverse_sql="-- Таблица shop_asexam_users была удалена"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS shop_asexam;",
            reverse_sql="-- Таблица shop_asexam была удалена"
        ),
    ]
