# Generated by Django 5.1.4 on 2025-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_options_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес доставки'),
        ),
    ]
