# Generated by Django 5.2.1 on 2025-05-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('honey', 'Мёд'), ('comb', 'Соты'), ('propolis', 'Прополис'), ('bee_pollen', 'Пыльца'), ('wax', 'Воск')], default='honey', max_length=20, verbose_name='Вид продукции'),
        ),
    ]
