# Generated by Django 5.2.1 on 2025-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contact_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.OrderItem', through_fields=('order', 'product'), to='shop.product', verbose_name='Товары в заказе'),
        ),
    ]
